version: '3.7'
services:
    database:
        image: 'mariadb:10.7.3'
        container_name: profit_dashboard_database
        environment:
            MYSQL_ROOT_PASSWORD: dev
            MYSQL_DATABASE: profit_dashboard
        ports:
            - 3306:3306
    adminer:
        build: docker/adminer
        container_name: profit_dashboard_adminer
        depends_on:
            - database
        ports:
            - 8080:8080
    app:
        build: docker/app
        container_name: profit_dashboard_app
        depends_on:
            - database
        volumes:
            - .:/var/www
            - ./docker/app/apache.conf:/etc/apache2/sites-available/000-default.conf
            - ./docker/app/entrypoint.sh:/home/docker-entrypoint.sh
        tty: true
        ports:
            - 8000:8000
        command: /home/docker-entrypoint.sh
    # localtunnel:
    #     image: efrecon/localtunnel
    #     depends_on:
    #         - app
    #     links:
    #         - app
    #     command:
    #         --local-host app --port 8000 -s profitdashboard
