version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev
    ports:
      - 3306:3306
    command: mysqld --general-log=1 --general-log-file=/var/log/mysql/general-log.log
